export const profanityFilter = (text) => {
  const textArray = text.split(" ");
  const profanities = [
    "arse",
    "arsehode",
    "ass",
    "bastard",
    "bitch",
    "bollocks",
    "bugger",
    "crap",
    "cunt",
    "damn",
    "dick",
    "douche",
    "fag",
    "fuck",
    "hell",
    "idiot",
    "jerk",
    "moron",
    "piss",
    "prick",
    "shit",
    "slut",
    "twat",
    "whore",
    "minge",
    "wank",
    "nigger",
    "cum",
    "shite",
    "dickhead",
  ];
  return textArray.find((word: string) => profanities.includes(word));
};
