import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useBasketStore } from "../store/basketStore";
import { Link } from "react-router-dom";
import styles from "./Basket.module.css";
const Basket = () => {
    const { items, removeItem, updateQuantity, totalPrice, clearBasket } = useBasketStore();
    if (items.length === 0) {
        return (_jsxs("div", { className: styles.emptyBasket, children: [_jsx("h2", { className: styles.emptyBasketTitle, children: "Your Basket" }), _jsx("p", { className: styles.emptyBasketText, children: "Your basket is empty" })] }));
    }
    return (_jsxs("div", { className: styles.basketContainer, children: [_jsxs("div", { className: styles.basketHeader, children: [_jsx("h2", { className: styles.basketTitle, children: "Your Basket" }), _jsx("button", { onClick: clearBasket, className: styles.clearButton, children: "Clear Basket" })] }), _jsx("div", { className: styles.itemsList, children: items.map((item, i) => (_jsxs("div", { className: styles.basketItem, children: [item.product.image && (_jsx("img", { src: item.product.image, alt: item.product.name, className: styles.productImage })), _jsxs("div", { className: styles.itemDetails, children: [_jsx("h3", { className: styles.productName, children: item.product.name }), _jsxs("p", { className: styles.price, children: ["\u00A3", item.product.price.toFixed(2)] }), _jsxs("div", { className: styles.quantityControl, children: [_jsx("button", { onClick: () => updateQuantity(item.product.id, item.quantity - 1), className: styles.quantityButton, children: "-" }), _jsx("span", { className: styles.quantityValue, children: item.quantity }), _jsx("button", { onClick: () => updateQuantity(item.product.id, item.quantity + 1), className: `${styles.quantityButton} ${styles.quantityButtonRight}`, children: "+" })] })] }), _jsxs("div", { className: styles.itemTotal, children: [_jsxs("p", { className: styles.totalPrice, children: ["\u00A3", (item.product.price * item.quantity).toFixed(2)] }), _jsx("button", { onClick: () => removeItem(item.product.id), className: styles.removeButton, children: "X" })] })] }, item.product.id + i))) }), _jsxs("div", { className: styles.checkoutSection, children: [_jsxs("div", { className: styles.totalContainer, children: [_jsx("span", { className: styles.totalLabel, children: "Total:" }), _jsxs("span", { className: styles.totalAmount, children: ["\u00A3", totalPrice().toFixed(2)] })] }), _jsx(Link, { to: '/checkout', className: styles.checkoutButton, children: "Proceed to Checkout" })] })] }));
};
export default Basket;
