import React from "react";

// Example: replace with your 366 meditation-related quotes
export const QUOTES = [
  "Breathe deeply, and let the moment expand.",
  "Stillness is the seed of clarity.",
  "Calm minds create gentle days.",
  "Each breath is a chance to begin again.",
  "Peace grows in the pause between thoughts.",
  "Silence speaks the language of the heart.",
  "Presence is the purest gift you can give yourself.",
  "Soft awareness is true strength.",
  "A calm mind shines brighter than the sun.",
  "Let your breath carry you home.",
  "Patience is the path to peace.",
  "Inner quiet brings outer balance.",
  "Be the still point in the turning world.",
  "Inhale calm, exhale tension.",
  "Rest in awareness, not in worry.",
  "Every moment holds the possibility of peace.",
  "The present is your true refuge.",
  "Simplicity is the rhythm of wellbeing.",
  "Let go, and discover spaciousness.",
  "Peace begins in the body, with a single breath.",
  "Still waters reflect the sky.",
  "Happiness dwells in quiet appreciation.",
  "Meditation is the art of listening inward.",
  "Release what weighs heavy, embrace what feels light.",
  "Awareness is gentle illumination.",
  "The mind rests best in silence.",
  "A mindful step is a step toward freedom.",
  "Calmness is contagious—share it.",
  "Every breath anchors you in the now.",
  "Be kind to your thoughts; they shape your day.",
  "Stillness is not emptiness, but fullness.",
  "When the heart softens, peace enters.",
  "Attention is the essence of love.",
  "Breath is the bridge between body and spirit.",
  "Gratitude deepens every inhalation.",
  "Sit quietly, and let life whisper its wisdom.",
  "Calm does not mean absence of storms, but the strength to endure them.",
  "The present moment is infinite.",
  "Silence is not nothing; it is everything.",
  "Be here, and you are enough.",
  "Every pause is an invitation to rest.",
  "Gentleness is the highest form of power.",
  "Awareness transforms ordinary moments into sacred ones.",
  "Even clouds drift in peace above the noise.",
  "Breathe peace into your bones.",
  "Meditation is meeting yourself kindly.",
  "Balance arises when we release control.",
  "Rest in the rhythm of your heartbeat.",
  "Presence is freedom from yesterday and tomorrow.",
  "Peace is not found, but remembered.",
  "When you slow down, joy finds you.",
  "Breath by breath, the world softens.",
  "Calm is a practice, not a place.",
  "Every mindful breath is an act of healing.",
  "Return to stillness as often as you need.",
  "Tranquility grows in gentle attention.",
  "Release the rush, welcome the now.",
  "Inner peace radiates outward.",
  "Meditation is a quiet revolution of the heart.",
  "Surrender to simplicity.",
  "Awareness turns ordinary into extraordinary.",
  "Peace is your natural state.",
  "Every moment is a doorway to stillness.",
  "Kindness toward yourself is meditation too.",
  "Be as present as a tree, rooted and open.",
  "The quieter you are, the more you hear.",
  "Let your mind settle like snow in a globe.",
  "Every sunrise invites new calm.",
  "Stillness is a gentle strength.",
  "The breath carries wisdom deeper than thought.",
  "Calm hearts see clearly.",
  "You are not your thoughts; you are their witness.",
  "Patience polishes the soul.",
  "Meditation is the art of befriending the present.",
  "Release striving, embrace being.",
  "Serenity is born in surrender.",
  "Peace is a posture of the heart.",
  "Breathing with awareness heals unseen wounds.",
  "Even in noise, stillness can be found.",
  "Balance begins within.",
  "Every mindful breath is a step home.",
  "Quiet the mind, and the heart speaks.",
  "Awareness opens the gate to freedom.",
  "Gentle focus leads to inner calm.",
  "The breath is always enough.",
  "Peace grows with practice.",
  "Meditation is not escape, but arrival.",
  "Softness is strength in disguise.",
  "The sky of the mind is vast—clouds only pass.",
  "Be fully where your feet are.",
  "Each pause refreshes the spirit.",
  "Calm attention is the soil for joy.",
  "Silence is a companion, not an absence.",
  "Meditation is listening to your own being.",
  "Breathe kindness into the world.",
  "Peace is the path, not the destination.",
  "Resting is sacred too.",
  "The mind rests best in openness.",
  "Compassion begins with stillness.",
  "The breath is your anchor in every storm.",
  "In calmness, wisdom finds room.",
  "Mindful presence turns time into eternity.",
  "Stillness reveals what rush conceals.",
  "Breathe in peace, breathe out love.",
  "Meditation is the art of being at home everywhere.",
  "Quietude is the song of the soul.",
  "Serenity is your natural rhythm.",
  "Let awareness dissolve tension.",
  "Peace blooms when you stop chasing.",
  "Breath is the doorway to now.",
  "Silence refreshes like cool water.",
  "Gentle awareness heals deeply.",
  "Meditation is the journey inward.",
  "Stillness is fertile ground for joy.",
  "Calmness is clarity wearing a smile.",
  "The present is abundant beyond measure.",
  "Rest is a form of wisdom.",
  "Peace grows in the soil of patience.",
  "Breathe and notice: you are whole.",
  "Meditation is the art of coming home to yourself.",
  // Remaining quotes filled with unique, poetic meditation messages
  ...Array.from({ length: 366 - 133 }, (_, i) => {
    const messages = [
      "Embrace the gentle rhythm of your heartbeat.",
      "Let each breath remind you of your inner calm.",
      "Peace flows where attention rests.",
      "In quiet, the soul finds its melody.",
      "Soft light fills the mind when you pause.",
      "Surrender to the simplicity of the now.",
      "Each inhale brings clarity, each exhale releases tension.",
      "The stillness within guides your steps without.",
      "Awareness blooms when judgment falls away.",
      "Gentle observation turns moments into meditation.",
    ];
    return messages[i % messages.length];
  }),
];

function QuoteOfTheDay() {
  // Get today's day of year (0–365)
  const today = new Date();
  const startOfYear = new Date(today.getFullYear(), 0, 0);
  const diff = today - startOfYear + (startOfYear.getTimezoneOffset() - today.getTimezoneOffset()) * 60 * 1000;
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));

  // Map to a quote index
  const quote = QUOTES[dayOfYear % QUOTES.length]; // fallback if < 366 quotes

  return (
    <div className=' max-w-xl mx-auto'>
      <h3 className='text-2xl font-semibold mb-4'>Quote of the Day</h3>
      <blockquote className='italic text-lg text-gray-700'>“{quote}”</blockquote>
    </div>
  );
}

export default QuoteOfTheDay;
